// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SayIt.Infrastructure.Data;

#nullable disable

namespace SayIt.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307093906_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SayIt.Core.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("emoji");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<int>("ThreadCount")
                        .HasColumnType("integer")
                        .HasColumnName("thread_count");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            Emoji = "🔥",
                            Name = "Hot Takes",
                            Slug = "hot-takes",
                            ThreadCount = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            Emoji = "🫣",
                            Name = "Confessions",
                            Slug = "confessions",
                            ThreadCount = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            Emoji = "💢",
                            Name = "Rants",
                            Slug = "rants",
                            ThreadCount = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            Emoji = "🧠",
                            Name = "Advice",
                            Slug = "advice",
                            ThreadCount = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000005"),
                            Emoji = "✨",
                            Name = "Dreams",
                            Slug = "dreams",
                            ThreadCount = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000006"),
                            Emoji = "🍵",
                            Name = "Spill the Tea",
                            Slug = "spill-the-tea",
                            ThreadCount = 0
                        });
                });

            modelBuilder.Entity("SayIt.Core.Entities.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("emoji");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("target_type");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("idx_reactions_target");

                    b.HasIndex("UserId", "TargetType", "TargetId", "Emoji")
                        .IsUnique()
                        .HasDatabaseName("idx_reactions_unique");

                    b.ToTable("reactions");
                });

            modelBuilder.Entity("SayIt.Core.Entities.Reply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ParentReplyId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_reply_id");

                    b.Property<string>("ReactionCount")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reaction_count");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentReplyId");

                    b.HasIndex("ThreadId", "CreatedAt")
                        .HasDatabaseName("idx_replies_thread");

                    b.ToTable("replies");
                });

            modelBuilder.Entity("SayIt.Core.Entities.Thread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime?>("AutoDeleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auto_delete_at");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("ReactionCount")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reaction_count");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("integer")
                        .HasColumnName("reply_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("AutoDeleteAt")
                        .HasDatabaseName("idx_threads_auto_delete")
                        .HasFilter("auto_delete_at IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_threads_created");

                    b.HasIndex("ChannelId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_threads_channel_created");

                    b.ToTable("threads");
                });

            modelBuilder.Entity("SayIt.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnonymousName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("anonymous_name");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("auth_provider");

                    b.Property<short>("AvatarIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("avatar_index");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email_hash");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("EmailHash")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("SayIt.Core.Entities.Reaction", b =>
                {
                    b.HasOne("SayIt.Core.Entities.Thread", null)
                        .WithMany("Reactions")
                        .HasForeignKey("ThreadId");

                    b.HasOne("SayIt.Core.Entities.User", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SayIt.Core.Entities.Reply", b =>
                {
                    b.HasOne("SayIt.Core.Entities.User", "Author")
                        .WithMany("Replies")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SayIt.Core.Entities.Reply", "ParentReply")
                        .WithMany("ChildReplies")
                        .HasForeignKey("ParentReplyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SayIt.Core.Entities.Thread", "Thread")
                        .WithMany("Replies")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ParentReply");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("SayIt.Core.Entities.Thread", b =>
                {
                    b.HasOne("SayIt.Core.Entities.User", "Author")
                        .WithMany("Threads")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SayIt.Core.Entities.Channel", "Channel")
                        .WithMany("Threads")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("SayIt.Core.Entities.Channel", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("SayIt.Core.Entities.Reply", b =>
                {
                    b.Navigation("ChildReplies");
                });

            modelBuilder.Entity("SayIt.Core.Entities.Thread", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SayIt.Core.Entities.User", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");

                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
